name: Run Backend Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example

    env:
      MONGO_URI: mongodb+srv://moolmans20013:9ZMo2N04RpSYvkI6@cluster0.lfx4knj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      PORT: 3000

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js for the backend folder
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies in the backend folder
      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      # Start the backend server in the background
      - name: Start the backend server
        working-directory: backend
        run: |
          npm run start &  # Start the backend server in the background
          sleep 5          # Wait for the server to initialize

      # Run tests in the backend folder
      - name: Run backend tests
        working-directory: backend
        run: npm test
